name: Deploy ECS (dev partner)

env:
  ENVIRONMENT: dev
  AWS_ECSPRESSO_ROLE_ARN: arn:aws:iam::450440358764:role/ecspressoGitHubActionsRole
  ECR_REGISTRY: 450440358764.dkr.ecr.ap-northeast-1.amazonaws.com

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'デプロイのみしたい場合に利用。存在するイメージタグを指定してください'
        required: false
      enable_image_scan:
        description: 'スキャンを必須にする'
        required: false
        default: false
        type: boolean
  # 5分おきに実行
  schedule:
    - cron:  '*/5 * * * *'

permissions:
  id-token: write
  contents: read

jobs:
  get-env-vars:
    name: 環境変数の取得
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
      AWS_ECSPRESSO_ROLE_ARN: ${{ env.AWS_ECSPRESSO_ROLE_ARN }}
      ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
    steps:
      - run: echo "workflow_callで呼び出された場合は、envの値が取得できないので、ここで取得します。"

  set-image-tag:
    name: イメージタグの作成or取得
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create-tag.outputs.TAG }}
      skip_build: ${{ steps.create-tag.outputs.SKIP_BUILD }}
    steps:
      - name: Create tag
        id: create-tag
        env:
          TZ: 'Asia/Tokyo'
        run: |
          if [ -z "${{ inputs.image_tag || '' }}" ] || [ "${{ github.event_name }}" == "schedule" ]; then
            echo TAG="${{ github.sha }}-$(date '+%Y%m%d%H%M')" >> $GITHUB_OUTPUT
            echo SKIP_BUILD=false >> $GITHUB_OUTPUT
          else
            echo TAG=${{ inputs.image_tag }} >> $GITHUB_OUTPUT
            echo SKIP_BUILD=true >> $GITHUB_OUTPUT
          fi